export default {
  article: {},
  "article-page": {},
  author: {},
  "author-page": {},
  "bootstrap-modal-content": {},
  "bootstrap-modal-content-page": {},
  notifications: {},
  "notifications-page": {},
  "reusable-content": {},
  "reusable-content-page": {},
  "hedera-tag": {},
  "hedera-tag-page": {},
  topic: {},
  "topic-page": {},
};
