export default {
  "bootstrap-modal-content": {},
  "bootstrap-modal-content-page": {},
  "hedera-article": {},
  "hedera-article-page": {},
  "hedera-author": {},
  "hedera-author-page": {},
  "hedera-notifications": {},
  "hedera-notifications-page": {},
  "hedera-reusable-content": {},
  "hedera-reusable-content-page": {},
  "hedera-tag": {},
  "hedera-tag-page": {},
  "hedera-topic": {},
  "hedera-topic-page": {},
};
