export default {
  "aside-widget": {},
  "bootstrap-columns-widget": {},
  "bootstrap-table-widget": {},
  "card-widget": {},
  "card-link-widget": {},
  "carousel-widget": {},
  "container-block-widget": {},
  "cover-block-widget": {},
  "definition-list-widget": {},
  "figure-widget": {},
  "hedera-button-widget": {},
  "hedera-image-widget": {},
  "horizontal-rule-widget": {},
  "html-widget": {},
  "list-widget": {},
  "list-group-widget": {},
  "newsletter-subscription-widget": {},
  "quote-widget": {},
  "reusable-content-blocks-widget": {},
  "spacer-widget": {},
  "teaser-link-widget": {},
  "testimonial-widget": {},
  "verse-widget": {},
  "page-modules": {
    options: {
      ignoreNoCodeWarning: true,
    },
  },
  "piece-modules": {
    options: {
      ignoreNoCodeWarning: true,
    },
  },
};
