export default {
  "bootstrap-card-widget": {},
  "bootstrap-card-link-widget": {},
  "bootstrap-carousel-widget": {},
  "bootstrap-columns-widget": {},
  "bootstrap-container-block-widget": {},
  "bootstrap-list-widget": {},
  "bootstrap-list-group-widget": {},
  "bootstrap-spacer-widget": {},
  "bootstrap-table-widget": {},
  "hedera-aside-widget": {},
  "hedera-button-widget": {},
  "hedera-cover-block-widget": {},
  "hedera-definition-list-widget": {},
  "hedera-figure-widget": {},
  "hedera-horizontal-rule-widget": {},
  "hedera-html-widget": {},
  "hedera-image-widget": {},
  "hedera-link-widget": {},
  "hedera-newsletter-subscription-widget": {},
  "hedera-quote-widget": {},
  "hedera-reusable-content-blocks-widget": {},
  "hedera-teaser-link-widget": {},
  "hedera-testimonial-widget": {},
  "hedera-verse-widget": {},
  "page-modules": {
    options: {
      ignoreNoCodeWarning: true,
    },
  },
  "piece-modules": {
    options: {
      ignoreNoCodeWarning: true,
    },
  },
};
